[package]
name = "hwid-license"
version = "0.1.0"
edition = "2021"

[dependencies]
winapi = { version = "0.3.9", features = ["winbase", "winnt", "minwindef", "winuser", "sysinfoapi", "fileapi"] }
raw-cpuid = "11.0.1"
sha256 = "1.3.0"